spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ias_dev
    username: postgres
    password: M@kinj@131194
    hikari:
      connection-timeout: 300000

#  jpa:
#    show-sql: true

  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration

