spring:
  application:
    name: identity-access-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ias
    username: postgres
    password: M@kinj@131194

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect