spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ias_test
    username: postgres
    password: M@kinj@131194
    hikari:
      connection-timeout: 30000

#  jpa:
#    show-sql: false

  flyway:
    enabled: true
    baseline-on-Migrate: false
    locations: classpath:db/migration